#!/bin/zsh

csv_location=${HOME}/.zoom-cli/meetings.csv

if [ ! -f $csv_location ]; then
    echo "Meetings file not found!" >&2
    exit 1
fi

{
    read -r meetingName
    read -r meetingLink
    read -r passcode
}<<<$( awk -F ';' -v code="$1" '{if (code == $2) {print $1; print $3; print $4}}' $csv_location )

if [[ ${#meetingLink} -eq 0 ]]; then
    echo "Meeting code not found!"
    exit 1
fi

echo -n $passcode | xclip -selection clipboard
echo "passcode for <$meetingName> copied to clipboard!"

xdg-open $meetingLink